sudo: required
services:
  - docker

before_install:
  - docker build -t aseelaldallal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aseelaldallal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  name: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-ca-central-1-307308598241"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
